import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/themes/catppuccin_latte.toml"
  #"~/.config/alacritty/catppuccin_frappe.toml"
  #"~/.config/alacritty/catppuccin_macchiato.toml"
  #"~/.config/alacritty/catppuccin_mocha.toml"
  "~/.config/alacritty/actual.toml"
  #"~/.config/alacritty/themes/everforest_dark.toml"
  #"~/.config/alacritty/themes/everforest_light.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
#dimensions = { columns = 80, lines = 25 } # for a single window
dimensions = { columns = 161, lines = 52 } # for a tmux-able window
padding.x = 10
padding.y = 10
#position = { x = 14, y = 115 }  # for a single window
position = { x = 323, y = 115 } # for a tmux-able window

decorations = "Full"
#decorations = "None"
#decorations = "Transparent"
#decorations = "Buttonless"

# Options are "Dark", "Light" and "None"
decorations_theme_variant = "None"

opacity = 0.50
#opacity = 0.25
blur = true

# This following option breaks the CSA Keyboard
#option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 15
