github.com:
    git_protocol: ssh
    users:
        MelvinQc542:
            oauth_token: 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
    user: MelvinQc542
    oauth_token: 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
