#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
os = '#ACB0BE'
black = 'transparent'
blue = '#77C0FF'
green = '#C0FFC0'
orange = '#FFC000'
red = '#FFC0C0'
white = '#C0C0C0'
yellow = '#FFFFC0'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'os'
style = 'plain'
foreground = 'p:os'
template = '{{.Icon}} '

[[blocks.segments]]
type = 'session'
style = 'plain'
template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
foreground = 'p:blue'

[[blocks.segments]]
type = 'path'
style = 'plain'
template = '  {{ path .Path .Location }} '
background = 'transparent'
foreground = 'p:white'

    [blocks.segments.properties]
    style = 'agnoster_short'

[[blocks.segments]]
style = 'plain'
foreground = 'p:os'
template = ''
type = 'text'

[[blocks.segments]]
type = 'root'
style = 'plain'
template = '  '
foreground = 'p:red'

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
foreground = 'p:white'

    [blocks.segments.properties]
    always_enabled = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'shell'
style = 'plain'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
foreground = 'p:white'

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_status = true
    fetch_upstream_icon = true

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '({{ div .Ms 1000 }}s)'

[[blocks.segments]]
type = 'node'
style = 'plain'
template = ' '
foreground = 'p:white'

    [blocks.segments.properties]
    display_mode = 'files'
    fetch_package_manager = false
    home_enabled = false

[[blocks.segments]]
type = 'go'
style = 'plain'
template = ' '
foreground = 'p:white'

    [blocks.segments.properties]
    fetch_version = false

[[blocks.segments]]
type = 'python'
style = 'plain'
template = ' '
foreground = 'p:white'

    [blocks.segments.properties]
    display_mode = 'files'
    fetch_version = false
    fetch_virtual_env = false

# Shell and time non-necessary
#[[blocks.segments]]
#type = 'shell'
#style = 'plain'
#template = ' <p:blue><b>{{ .Name }}</b></> '
#foreground = 'p:white'

#[[blocks.segments]]
#type = 'time'
#style = 'plain'
#template = 'at <p:blue><b>{{ .CurrentDate | date "15:04" }}</b></>'
#foreground = 'p:white'

[[tooltips]]
type = 'aws'
tips = ['aws']
style = 'plain'
template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
foreground = 'p:white'

  [tooltips.properties]
  display_default = true

[[tooltips]]
type = 'az'
tips = ['az']
style = 'plain'
template = '  {{ .Name }} '
foreground = 'p:white'

  [tooltips.properties]
  display_default = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  '{{ if gt .Code 0 }}p:red{{ end }}',
  '{{ if eq .Code 0 }}p:blue{{ end }}',
]
background = 'transparent'
template = '❯'

[transient_prompt]
foreground_templates = [
  '{{ if gt .Code 0 }}p:red{{ end }}',
  '{{ if eq .Code 0 }}p:blue{{ end }}',
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
template = ' ❯❯ '
foreground = 'p:yellow'
